---
title: "NDS_Visualizations"
author: "Kateri Salk"
date: "12/30/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(sf)
library(ggmap)
library(maps)
library(openxlsx)
library(cowplot)

theme_set(theme_classic())
options(scipen = 4)
```

## Upload processed data 
```{r}
# experimental results 
siteyear <- read.csv("../../DataProcessing/R_DataProcessing/CSVs/SiteYear.csv")
# statewide dataset for comparison
COstatewidedata <- read.xlsx("../../../Source/Obtained/COStatewideWQData_Streams_20201222.xlsx", sheet = "Data")

# color hemispherical photo data
hemiphoto.df <- read.csv("../../DataProcessing/R_Light/Output/HemiPhotoOutput.csv")
#black and white hemispherical photo data
hemiphoto.df.bw <- read.csv("../../DataProcessing/R_Light/Output/HemiPhotoOutput_BW.csv")

# filter for HDR exposure setting
hemiphoto.HDR <- hemiphoto.df %>%
	filter(Replicate == "Sampling,HDR") %>%
	select(Site, SiteCode, CanOpen, LAI)

hemiphoto.df.bw <- hemiphoto.df.bw %>%
	arrange(CanOpen)%>%
  mutate(Site = factor(Site, levels = Site))

hemiphoto.df.bw$Site <- with(hemiphoto.df.bw,factor(Site,levels=unique(Site)))

colnames(hemiphoto.df.bw)[4:5] <- c("CanOpen.bw", "LAI.bw")

# create a summary data frame with all hemispherical photo data
hemiphoto.summary <- hemiphoto.df %>%
  group_by(Date, Site, SiteCode) %>%
  summarise(minCanOpen = min(CanOpen), 
            maxCanOpen = max(CanOpen), 
            minLAI = min(LAI), 
            maxLAI = max(LAI)) %>%
  full_join(., hemiphoto.HDR) %>%
	full_join(., hemiphoto.df.bw) %>%
  arrange(CanOpen.bw) %>%
  mutate(Site = factor(Site, levels = Site))

hemiphoto.summary$Site <- with(hemiphoto.summary,factor(Site,levels=unique(Site)))

```

## Spatial
```{r}
# Create CO base layer
states <- st_as_sf(map(database = "state", plot = TRUE, fill = TRUE, col = "white"))
CO <- filter(states, ID == "colorado") 
st_crs(CO)

# Create CO HUC8 watershed layer
HUC8 <- st_read("./CO_Shapefile/wbdhu8.dbf")
st_crs(HUC8)
CO.HUC8 <- HUC8 %>%
	st_transform(crs = st_crs(4326)) %>%
	st_intersection(CO)

# Create experimental site layer
sites <- siteyear %>%
	select(SiteID, Year, NRR, PRR, TN_mgL, TP_mgL, Slope_AvgBasinwide_pct, Lat, Long) %>%
	distinct() %>%
	left_join(., hemiphoto.summary, by = c("SiteID" = "SiteCode"))

sites.sf <- st_as_sf(sites, coords = c("Long", "Lat"), crs = 4326)
```


## Visualizations
### Light
```{r}
ggplot(hemiphoto.df, aes(x = Replicate, y = LAI)) +
  geom_boxplot(outlier.color = "white") +
  geom_jitter() +
  labs(x = "Exposure setting", y = "Leaf Area Index")
# ggsave("./Output/LAI_boxplot.jpg", dpi = 300, 
#        height = 3.5, width = 4, units = "in")

ggplot(hemiphoto.df, aes(x = Replicate, y = CanOpen)) +
  geom_boxplot() +
  labs(x = "Exposure setting", y = "Canopy Openness")
# ggsave("./Output/CanOpen_boxplot.jpg", dpi = 300, 
#        height = 3.5, width = 4, units = "in")

ggplot(hemiphoto.df, aes(x = CanOpen, y = LAI, color = Replicate)) +
  geom_point(alpha = 0.7, size = 2) +
  scale_color_viridis_d() +
  labs(x = "Canopy Openness", y = "Leaf Area Index", color = "Exposure Setting")
# ggsave("./Output/CanOpen_LAI_scatterplot.jpg", dpi = 300, 
#        height = 3.5, width = 4, units = "in")
   
ggplot(hemiphoto.summary) +
  geom_segment(aes(y = Site, yend = Site, x = minCanOpen, xend = maxCanOpen),
               color = "#868cc6", size = 1) +
  geom_point(aes(y = Site, x = CanOpen), color = "#404788FF", size = 2) +
  geom_point(aes(y = Site, x = CanOpen.bw), size = 2) +
  labs(x = "Canopy Openness", y = "")
# ggsave("./Output/CanOpen_lollipop.jpg", dpi = 300, 
#        height = 5, width = 5, units = "in")
```

### Spatial
```{r}

ggplot(CO) +
	geom_sf(fill = "white") +
	geom_sf(data = HUC8, alpha = 0, color = "gray") +
	geom_sf(data = subset(sites.sf, Year == 2014), aes(color = CanOpen.bw)) +
	labs(color = "Canopy Openness") +
	scale_color_viridis_c(end = 0.8) +
	theme(legend.position = "top")
# ggsave("./Output/Map_light.jpg", dpi = 300, 
#        height = 5, width = 5.5, units = "in")

ggplot(CO) +
	geom_sf(fill = "white") +
	geom_sf(data = HUC8, alpha = 0, color = "gray") +
	geom_sf(data = sites.sf, aes(color = log(TN_mgL), shape = as.factor(Year))) +
	labs(color = "log(TN (mg/L))", shape = "Year") +
	scale_color_viridis_c(end = 0.8, direction = -1) +
	theme(legend.position = "top", legend.spacing.x = unit(0.01, "cm"))
# ggsave("./Output/Map_TN.jpg", dpi = 300, 
#        height = 5, width = 5.5, units = "in")

ggplot(CO) +
	geom_sf(fill = "white") +
	geom_sf(data = HUC8, alpha = 0, color = "gray") +
	geom_sf(data = sites.sf, aes(color = log(TP_mgL), shape = as.factor(Year))) +
	labs(color = "log(TP (mg/L))", shape = "Year") +
	scale_color_viridis_c(end = 0.8, direction = -1) +
	theme(legend.position = "top", legend.spacing.x = unit(0.01, "cm"))
# ggsave("./Output/Map_TP.jpg", dpi = 300, 
#        height = 5, width = 5.5, units = "in")

ggplot(CO) +
	geom_sf(fill = "white") +
	geom_sf(data = HUC8, alpha = 0, color = "gray") +
	geom_sf(data = sites.sf, aes(color = NRR, shape = as.factor(Year))) +
	labs(color = "N Response Ratio", shape = "Year") +
	scale_color_viridis_c(end = 0.8, direction = -1) +
	theme(legend.position = "top", legend.spacing.x = unit(0.01, "cm"))
# ggsave("./Output/Map_NRR.jpg", dpi = 300, 
#        height = 5, width = 5.5, units = "in")

ggplot(CO) +
	geom_sf(fill = "white") +
	geom_sf(data = HUC8, alpha = 0, color = "gray") +
	geom_sf(data = sites.sf, aes(color = PRR, shape = as.factor(Year))) +
	labs(color = "P Response Ratio", shape = "Year") +
	scale_color_viridis_c(end = 0.8, direction = -1) +
	theme(legend.position = "top", legend.spacing.x = unit(0.01, "cm"))
# ggsave("./Output/Map_PRR.jpg", dpi = 300, 
#        height = 5, width = 5.5, units = "in")

ggplot(CO) +
	geom_sf(fill = "white") +
	geom_sf(data = HUC8, alpha = 0, color = "gray") +
	geom_sf(data = sites.sf, aes(color = Slope_AvgBasinwide_pct, shape = as.factor(Year))) +
	labs(color = "Watershed slope (%)", shape = "Year") +
	scale_color_viridis_c(end = 0.8, direction = -1) +
	theme(legend.position = "top", legend.spacing.x = unit(0.01, "cm"))
# ggsave("./Output/Map_slope.jpg", dpi = 300, 
#        height = 5, width = 5.5, units = "in")

```

### Comparison boxplots
```{r}
TNstatewide <-
ggplot(COstatewidedata, aes(y = TNSum)) +
  geom_boxplot() +
  scale_y_log10(limits = c(0.00005, 55)) +
  labs(y = "TN (mg/L)", title = "Statewide Data") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

TN_NDS <-
ggplot(siteyear, aes(y = TN_mgL)) +
  geom_boxplot() +
  scale_y_log10(limits = c(0.00005, 55)) +
  labs(y = "", title = "NDS study") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), 
        axis.text.y = element_blank())

plot_grid(TNstatewide, TN_NDS, nrow = 1, rel_widths = c(1.1, 1))
# ggsave("./Output/TNcomparison.jpg", dpi = 300, 
#        width = 4, height = 3.5, units = "in")

TPstatewide <-
ggplot(COstatewidedata, aes(y = TP)) +
  geom_boxplot() +
  scale_y_log10(limits = c(0.001, 21)) +
  labs(y = "TP (mg/L)", title = "Statewide Data") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

TPNDS <-
ggplot(siteyear, aes(y = TP_mgL)) +
  geom_boxplot() +
  scale_y_log10(limits = c(0.001, 21)) +
  labs(y = "", title = "NDS study") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), 
        axis.text.y = element_blank())

plot_grid(TPstatewide, TPNDS, nrow = 1, rel_widths = c(1.1, 1))
# ggsave("./Output/TPcomparison.jpg", dpi = 300, 
#        width = 4, height = 3.5, units = "in")
```

